trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  location: 'westeurope'
  resourceGroupName: 'rg-from-pipeline'
  storageAccountName: 'storacctpipeline123'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'PIPELINE-DEPLOY'  # Replace this
    subscriptionId: '7b427448-867e-4f5c-8c16-c37f1ff70272'                            # Replace this
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: 'mainTemplate.json'
    deploymentMode: 'Incremental'
    parameters: |
      -resourceGroupName "$(resourceGroupName)"
      -location "$(location)"
      -storageAccountName "$(storageAccountName)"
